import type { Locale } from "./localization";

const copy = {
  "zh-CN": {
    importDocument: "Prompt 原文", importHint: "粘贴完整 Markdown / Frontmatter",
    importPlaceholder: "---\ntitle: 示例标题\ncategory: 分类\n---\n# 示例标题\n## Prompt\n在这里粘贴完整 Prompt…",
    reparse: "重新解析", dropOrPaste: "也可拖拽图片到这里，或用 Ctrl+V / Command+V 粘贴。",
    importSummary: "解析结果", summaryEmpty: "粘贴原文后显示解析结果。", willCreate: "将新建",
    variableCount: "变量数", imageState: "图片状态", importErrors: "需要修正", importWarnings: "提示",
    advancedEdit: "高级编辑", importIssue: { title: "缺少标题", prompt: "缺少 Prompt 正文",
      category: "缺少分类", metadata: "元数据或原文过长", variables: "变量过多", frontmatter: "未找到 Frontmatter，已尝试解析正文",
      created_at: "created_at 格式无法识别" },
    basicInformation: "基础信息", coreMetadata: "标识与分类", sourceContent: "原文内容", translationHint: "可选译文", variableFormat: "JSON 编辑",
    lifecycle: "生命周期", createdAt: "创建时间", neverPublished: "尚未发布", contentChecks: "已保存内容校验", checkSource: "原文必填内容", checkVariables: "变量与正文一致", checkTranslation: "译文变量一致", checkImage: "图片元数据完整", checkPassed: "通过", checkNeedsAttention: "需检查", checkSavedOnly: "校验基于已保存内容；修改后请先保存。", imageOriginalKey: "原图 key", imagePreviewKey: "预览图 key", imageMime: "原图 MIME", imageOriginalSize: "原图尺寸与字节", imagePreviewSize: "预览图尺寸与字节", imageGenerated: "原图及 WebP 预览会在创建前上传。", readOnly: "已删除内容仅供查看。",
    create: "新建 Prompt", createDraft: "创建草稿", sourceLanguage: "原文语言", chooseLanguage: "选择语言",
    chooseCategory: "选择分类", uploadImage: "上传图片", originalImage: "选择原图（JPEG、PNG、WebP，最大 20 MiB）",
    chooseImage: "请选择原图，系统将生成最长边不超过 768px 的 WebP 预览图。",
    uploading: "正在处理并上传图片…", uploadReady: "原图与预览图已上传，可以创建草稿。",
    uploadFailed: "图片处理或上传失败，请重新选择。", previewImage: "预览图",
    missingUpload: "图片上传不完整或已失效，请重新选择。", tooLarge: "图片超过大小限制。",
    prompts: "Prompt 管理", empty: "暂无 Prompt", edit: "编辑", previewPrompt: "预览", back: "返回列表",
    slug: "Slug", title: "标题", status: "状态", category: "分类", model: "模型",
    ratio: "画幅", publishedAt: "首次发布时间", updatedAt: "更新时间",
    draft: "草稿", published: "已发布", deleted: "已删除",
    original: "原文", translation: "译文", description: "描述", template: "Prompt 正文",
    imageAlt: "图片说明", imageMetadata: "图片元数据（只读）", replaceImage: "替换图片",
    replaceReady: "新原图与预览图已上传，可以替换当前图片。",
    variables: "变量 JSON", example: "JSON 示例", variablesHelp: "使用数组。text 的 options 必须为 null；select 的 options 为 [{\"value\":\"stable_key\",\"labels\":{\"zh-CN\":\"中文\",\"en-US\":\"English\"}}]。key 必须与原文和译文的 {{key}} 一致。",
    translationMode: "译文状态", present: "保存完整译文", remove: "清空译文",
    tags: "标签", save: "保存修改", publish: "发布", withdraw: "撤回", softDelete: "软删除",
    saveFirst: "发布只检查已保存的版本；修改表单后请先保存。",
    slugFrozen: "首次发布后 Slug 永久冻结。",
    invalid: "输入无效，请检查必填字段、变量 JSON、选项及译文。",
    missing: "Prompt 不存在。", conflict: "Slug 或分类/标签引用冲突，或当前状态不允许此操作。",
    deletedError: "已删除的 Prompt 不允许再修改。", tokens: "原文、译文中的 token 必须与变量 key 集合完全一致。",
    failed: "保存失败，请稍后重试。",
  },
  "en-US": {
    importDocument: "Prompt document", importHint: "Paste complete Markdown / Frontmatter",
    importPlaceholder: "---\ntitle: Example title\ncategory: Category\n---\n# Example title\n## Prompt\nPaste the complete prompt here…",
    reparse: "Parse again", dropOrPaste: "You can also drop an image here or paste it with Ctrl+V / Command+V.",
    importSummary: "Parsed summary", summaryEmpty: "Paste a document to see the parsed result.", willCreate: "Will create",
    variableCount: "Variables", imageState: "Image status", importErrors: "Fix these", importWarnings: "Notes",
    advancedEdit: "Advanced edit", importIssue: { title: "Missing title", prompt: "Missing prompt body",
      category: "Missing category", metadata: "Metadata or document is too long", variables: "Too many variables", frontmatter: "No Frontmatter; parsed the body",
      created_at: "Could not parse created_at" },
    basicInformation: "Basic Information", coreMetadata: "Identity & taxonomy", sourceContent: "Source Content", translationHint: "Optional translation", variableFormat: "JSON editor",
    lifecycle: "Lifecycle", createdAt: "Created", neverPublished: "Not published", contentChecks: "Saved content checks", checkSource: "Required source content", checkVariables: "Variables match template", checkTranslation: "Translation keys match", checkImage: "Image metadata complete", checkPassed: "Pass", checkNeedsAttention: "Check", checkSavedOnly: "Checks use saved content. Save changes first.", imageOriginalKey: "Original key", imagePreviewKey: "Preview key", imageMime: "Original MIME", imageOriginalSize: "Original dimensions & bytes", imagePreviewSize: "Preview dimensions & bytes", imageGenerated: "Original and WebP preview upload before creation.", readOnly: "Deleted content is read only.",
    create: "New prompt", createDraft: "Create draft", sourceLanguage: "Source language", chooseLanguage: "Choose language",
    chooseCategory: "Choose category", uploadImage: "Upload image", originalImage: "Choose original (JPEG, PNG, WebP; up to 20 MiB)",
    chooseImage: "Choose an original image. A WebP preview up to 768px will be generated.",
    uploading: "Processing and uploading images…", uploadReady: "Original and preview are uploaded. You can create the draft.",
    uploadFailed: "Image processing or upload failed. Choose an image again.", previewImage: "Preview image",
    missingUpload: "Image upload is incomplete or expired. Choose an image again.", tooLarge: "Image exceeds the size limit.",
    prompts: "Prompt management", empty: "No prompts yet", edit: "Edit", previewPrompt: "Preview", back: "Back to list",
    slug: "Slug", title: "Title", status: "Status", category: "Category", model: "Model",
    ratio: "Ratio", publishedAt: "First published", updatedAt: "Updated",
    draft: "Draft", published: "Published", deleted: "Deleted",
    original: "Source", translation: "Translation", description: "Description", template: "Prompt body",
    imageAlt: "Image alt", imageMetadata: "Image metadata (read only)", replaceImage: "Replace image",
    replaceReady: "New original and preview are uploaded. You can replace the current image.",
    variables: "Variables JSON", example: "JSON example", variablesHelp: "Use an array. text requires options: null; select requires options: [{\"value\":\"stable_key\",\"labels\":{\"zh-CN\":\"中文\",\"en-US\":\"English\"}}]. Keys must match {{key}} in source and translation.",
    translationMode: "Translation", present: "Save complete translation", remove: "Clear translation",
    tags: "Tags", save: "Save changes", publish: "Publish", withdraw: "Withdraw", softDelete: "Soft delete",
    saveFirst: "Publish checks the saved version. Save form changes first.",
    slugFrozen: "Slug is permanently frozen after first publication.",
    invalid: "Invalid input. Check required fields, variables JSON, options and translation.",
    missing: "Prompt not found.", conflict: "Slug or taxonomy reference conflict, or action is unavailable in this state.",
    deletedError: "Deleted prompts cannot be changed.", tokens: "Source and translation tokens must match variable keys exactly.",
    failed: "Save failed. Please try again.",
  },
} as const;
export function adminPromptCopy(locale: Locale) { return copy[locale]; }
