import type { Locale } from "./localization";

const copy = {
  "zh-CN": {
    explore: "探索",
    search: "搜索 Prompt、风格、模型或标签",
    searchButton: "搜索",
    filters: "筛选",
    allCategories: "全部分类",
    allTags: "全部标签",
    allModels: "全部模型",
    allRatios: "全部比例",
    allLanguages: "全部语言",
    category: "分类",
    model: "模型",
    ratio: "画幅比例",
    sourceLanguage: "Prompt 语言",
    apply: "应用",
    clear: "清除条件",
    newest: "最新",
    emptyTitle: "没有找到 Prompt",
    emptyDescription: "试试其他关键词或清除筛选条件。",
    previous: "上一页",
    next: "下一页",
    page: "第 {page} 页，共 {total} 页",
    language: "界面语言",
    metaTitle: "探索 Prompt · PromptVault",
    metaDescription: "按分类、模型和画幅探索图片 Prompt。",
    errorTitle: "出错了",
    errorDescription: "请求暂时无法完成。",
    notFound: "没有找到该页面。",
    backToExplore: "返回探索",
    tags: "标签",
    categoryMetaDescription: "探索「{name}」分类中的图片 Prompt。",
    tagMetaDescription: "探索「{name}」标签下的图片 Prompt。",
    emptyTaxonomyTitle: "暂无 Prompt",
    emptyTaxonomyDescription: "这里还没有已发布的 Prompt。",
    customizePrompt: "自定义 Prompt 变量",
    reset: "重置",
    selectPlaceholder: "请选择",
    promptBody: "Prompt 正文",
    promptLanguage: "Prompt 内容语言",
    original: "原文",
    copyPrompt: "复制 Prompt",
    copied: "已复制",
    copyFailed: "复制失败，请重试",
    adminTitle: "后台",
    adminReady: "管理员访问已通过验证。",
  },
  "en-US": {
    explore: "Explore",
    search: "Search prompts, styles, models, or tags",
    searchButton: "Search",
    filters: "Filters",
    allCategories: "All categories",
    allTags: "All tags",
    allModels: "All models",
    allRatios: "All ratios",
    allLanguages: "All languages",
    category: "Category",
    model: "Model",
    ratio: "Aspect ratio",
    sourceLanguage: "Prompt language",
    apply: "Apply",
    clear: "Clear filters",
    newest: "Newest",
    emptyTitle: "No prompts found",
    emptyDescription: "Try another search or clear the filters.",
    previous: "Previous",
    next: "Next",
    page: "Page {page} of {total}",
    language: "Interface language",
    metaTitle: "Explore prompts · PromptVault",
    metaDescription: "Explore image prompts by category, model, and aspect ratio.",
    errorTitle: "Something went wrong",
    errorDescription: "The request could not be completed.",
    notFound: "The requested page could not be found.",
    backToExplore: "Back to Explore",
    tags: "Tags",
    categoryMetaDescription: "Explore image prompts in {name}.",
    tagMetaDescription: "Explore image prompts tagged {name}.",
    emptyTaxonomyTitle: "No prompts yet",
    emptyTaxonomyDescription: "There are no published prompts here yet.",
    customizePrompt: "Custom Prompt Variables",
    reset: "Reset",
    selectPlaceholder: "Select an option",
    promptBody: "Prompt text",
    promptLanguage: "Prompt content language",
    original: "Original",
    copyPrompt: "Copy Prompt",
    copied: "Copied",
    copyFailed: "Copy failed. Please try again.",
    adminTitle: "Admin",
    adminReady: "Administrator access is verified.",
  },
} as const;

export function uiCopy(locale: Locale) {
  return copy[locale];
}


export const adminTaxonomy = {
  "zh-CN": {
    navigation: "后台导航", categories: "分类", tags: "标签",
    create: "新建", save: "保存", delete: "删除", edit: "编辑", empty: "暂无条目。",
    slug: "Slug（创建后不可修改）", sourceLanguage: "原文语言",
    translationLanguage: "译文语言", chooseLanguage: "请选择原文语言", name: "名称", description: "描述",
    sortOrder: "排序值", translationName: "译文名称", translationDescription: "译文描述",
    original: "原文", translation: "译文", optional: "留空则不保存译文",
    invalid: "输入无效。请检查 slug、语言、名称、描述和排序值。",
    missing: "条目不存在，可能已被删除。",
    duplicate: "Slug 已被使用。",
    referenced: "仍有 Prompt 引用该条目，无法删除。",
    failed: "保存失败，请稍后重试。",
  },
  "en-US": {
    navigation: "Admin navigation", categories: "Categories", tags: "Tags",
    create: "Create", save: "Save", delete: "Delete", edit: "Edit", empty: "No entries yet.",
    slug: "Slug (fixed after creation)", sourceLanguage: "Source language",
    translationLanguage: "Translation language", chooseLanguage: "Select source language", name: "Name", description: "Description",
    sortOrder: "Sort order", translationName: "Translated name", translationDescription: "Translated description",
    original: "Source", translation: "Translation", optional: "Leave blank to remove the translation",
    invalid: "Invalid input. Check the slug, languages, name, description, and sort order.",
    missing: "This entry no longer exists.",
    duplicate: "This slug is already in use.",
    referenced: "A Prompt still uses this entry, so it cannot be deleted.",
    failed: "Could not save. Please try again later.",
  },
} as const;

export function adminTaxonomyCopy(locale: Locale) {
  return adminTaxonomy[locale];
}



